### ISSUE TITLE
Improve the Footer + misc

### ISSUE THREAD

**Issue by nullity00** [nullity00/zacademy-site#6]
![image](https://github.com/nullity00/zacademy-site/assets/70228821/71d6d02c-05b8-492f-8a56-4d0b27d9c231)

## TODO

- [x] Replace the text with social media icons 
- [x] Add a shortcut to pages & other domains
- [ ] Generate Terms & Conditions , Privacy policy & add link to those 
- [ ] Create a 404 page
